import { StyleSheet } from "react-native";
import { moderateScale } from "react-native-size-matters";

export const colors = {
  primaryColor: "#0000A0",
  secondaryColor: "#B3B4B8",
  white: "white",
  grey: "#707070",
  darkGrey: "#444444",
  black: "#161616",
  red: "red",
  theme: "#FF5A01",
  otp: "#B5BBC9",
  opacity: "#00000075",
  accept: "#00C851",
  complete: "#007E33",
  cancel: "#FF4444",
  reject: "#CC0000",
  pending: "#FF8800",
  served: "#007BFF",
  preparing: "#17A2B8",
  blue: "#130F49",
  pink: "#DF0E57",
  lightPurple: "#7157DB",
  purple: "#392151",
  lightTheme: "#FFC8AB",
  light: "rgba(255, 89, 0, 0.1)",
};

export const images = {
  "ac.png": require("../assets/images/air-conditioner.png"),
  "mobile.png": require("../assets/images/iphone.png"),
  "electricity.png": require("../assets/images/plug.png"),
  "elevator.png": require("../assets/images/elevator.png"),
  "plumb.png": require("../assets/images/pipe.png"),
  "car.png": require("../assets/images/sport-car.png"),
  "decoration.png": require("../assets/images/spatula.png"),
  "tiles.png": require("../assets/images/stairs.png"),
  "paint.png": require("../assets/images/paint-brush.png"),
  "router.png": require("../assets/images/networking.png"),
  "laundary.png": require("../assets/images/washing-machine.png"),
  "camera.png": require("../assets/images/cctv-camera.png"),
  "carpenter.png": require("../assets/images/hand-saw.png"),
  "metal.png": require("../assets/images/blacksmith.png"),
  "alumnium.png": require("../assets/images/window.png"),
  "garden.png": require("../assets/images/gardening.png"),
  "truck.png": require("../assets/images/delivery-truck.png"),
  Selecting: require("../assets/icons/selecting.png"),
  Arrow: require("../assets/icons/arrowRight.png"),
  Location: require("../assets/icons/location.png"),
  Arrow_Down: require("../assets/icons/arrow_down.png"),
  Menu: require("../assets/icons/menu.png"),
  Logo: require("../assets/images/logo.png"),
  Arrow_Right: require("../assets/icons/arrow-right.png"),
  Arrow_Left: require("../assets/icons/arrow-left.png"),
  Arrow_Next: require("../assets/icons/next.png"),
  Phone: require("../assets/icons/phone.png"),
  WhatsApp: require("../assets/icons/whatsapp.png"),
  Call: require("../assets/icons/call.png"),
  Sound: require("../assets/icons/sound.png"),
  HidePassword: require("../assets/icons/hidePassword.png"),
  ShowPassword: require("../assets/icons/showPassword.png"),
  LoginLogo: require("../assets/images/loginLogo.png"),
  Home: require("../assets/icons/home.png"),
  FooterCall: require("../assets/icons/footerCall.png"),
  FooterWhatsApp: require("../assets/icons/footerWhatsApp.png"),
  Marker: require("../assets/icons/marker.png"),
};

export const fontSizes = {
  xl: 20,
  l: 16,
  m: 14,
  s: 12,
  xs: 10,
};

export const theme = StyleSheet.create({
  greyBg: { backgroundColor: colors.white },
  container: {
    padding: moderateScale(10),
    margin: 10,
  },
  infoTitle: {
    width: "99%",
    textAlign: "center",
    margin: 10,
    marginBottom: 0,
    color: colors.darkGrey,
    padding: 10,
    alignSelf: "center",
  },
  headerButtonLeft: { padding: 15, paddingLeft: 20 },
  headerButtonRight: { padding: 15, paddingRight: 20 },
  button: { alignSelf: "center", margin: moderateScale(10), width: "90%" },
  center: { alignSelf: "center" },
  end: { alignSelf: "flex-end" },
  p1: { padding: 10 },
  p2: { padding: 20 },
  p3: { padding: 30 },
  p4: { padding: 40 },
  pL1: { paddingLeft: 10 },
  pL2: { paddingLeft: 20 },
  pL3: { paddingLeft: 30 },
  pL4: { paddingLeft: 40 },
  pR1: { paddingRight: 10 },
  pR2: { paddingRight: 20 },
  pR3: { paddingRight: 30 },
  pR4: { paddingRight: 40 },
  pT1: { paddingTop: 10 },
  pT2: { paddingTop: 20 },
  pT3: { paddingTop: 30 },
  pT4: { paddingTop: 40 },
  pB1: { paddingBottom: 10 },
  pB2: { paddingBottom: 20 },
  pB3: { paddingBottom: 30 },
  pB4: { paddingBottom: 40 },
  m1: { margin: 10 },
  m2: { margin: 20 },
  m3: { margin: 30 },
  m4: { margin: 40 },
  mR1: { marginRight: 10 },
  mT1: { marginTop: 10 },
  mT2: { marginTop: 20 },
  mT3: { marginTop: 30 },
  mT4: { marginTop: 40 },
  mB1: { marginBottom: 10 },
  mB2: { marginBottom: 20 },
  mB3: { marginBottom: 30 },
  mB4: { marginBottom: 40 },
});

export const pickerStyle = {
  mB1: StyleSheet.create({
    inputIOS: theme.mB1,
    inputAndroid: theme.mB1,
  }),
};

export const opacities = {
  primary: 0.87,
  secondary: 0.54,
};
